### ISSUE TITLE
Questions about the .jpg WSIs resolution

### ISSUE THREAD

**Issue by pzSuen** [bupt-ai-cz/BALNMP#1]
Hello,
Thank you for your selfless data sharing,
But it seems you only provide `.jpg` WSIs without telling the resolution.

So, can you tell me the resolution of the data conversion?

**Comment by pzSuen** [comment]
And info about the scanner and the pixel size, like this `The slides were scanned with an Aperio AT2 scanner at 0:25 μm/pixel using a magnification factor of 40 × to result in WSIs`.

Thank you very much!

**Comment by super233** [comment]
Hi pzSuen, thanks for your interest in our BCNB Dataset.

The resolution information can be obtained by reading `.jpg` files directly.

The slides were scanned with Iscan Coreo pathologic scanner, and the WSIs were viewed at 200x magnification using Image Viewer software.

If you have any other questions, you can reopen this issue or contact us directly.
