### ISSUE TITLE
Global-Chem Partnership with BALNMP

### ISSUE THREAD

**Issue by Sulstice** [bupt-ai-cz/BALNMP#2]
Hello,

My name is Suliman Sharif and I am author of a python package called Global-Chem - A Dictionary from common chemical names to their molecular definition.

We have been keeping tracking of your as part of our medical database resources and noticed it went down with our monitor:

https://github.com/Sulstice/Uptime-Medical-Informatics

I want to know if you would like us to host your data at no cost to you to ensure the database is maintained for however long as part of our open source chemical database network. This is to build our knowledge graph in how chemical data relates to cancer imaging. 

The data would still be maintained by you. Would that be something you would be interested in?

Thank you,
-Suliman

**Comment by super233** [comment]
Hi, thanks for your attention, our database resources is always available, and we do not have plan to host our data in other platforms.
